### ISSUE TITLE
Documentation omission, relies on Yahoo API

### ISSUE THREAD

**Issue by neuhaus** [andretf/nanofeed#6]
The documentation says "no dependencies", however this library depends on the Yahoo API.

This makes the library unusable for projects where the yahoo API is inaccessible.

**Comment by andretf** [comment]
Thank you for your observation. I let implicit that "no dependencies" referred to 3rd party client libraries. I have clarified documentation.

It uses Yahoo! API because as a client script it have no reliable way to browser get content directly from url. Server may have CORS disabled. There is no option but to rely on a intermediate server. I will open a improvement ticket to add option to change intermediate server or cascade servers on error.

Yahoo! API has been losing reliability as it constantly goes down or change definitions without warning.
You can change it to use CORS workaround websites such as AnyOrigin or WhateverOrigin.
